[user_defines]
###########################
# Custom Definitions      #
###########################
sbst_dir = "../../cv32e40p/sbst"
test_dir = "../../cv32e40p/sbst/tests"
root_dir = "../../cv32e40p"
run_dir = "../../cv32e40p/run/vc-z01x"

[isa]
###########################
# ISALANG Location        #
###########################
isa_file = "../../langs/riscv.isa"

[assembly_sources]
###########################
# STL Sources             #
###########################
sources = [
  '%test_dir%/test1.S',
]

[cross_compilation]
###########################
# Cross Compilation       #
###########################
instructions = [
  'make -C %sbst_dir% clean',
  'make -C %sbst_dir% all'
]

[vcs_hdl_compilation]
###########################
# HDL Sources Compilation #
###########################
instructions = []

[vcs_logic_simulation]
###########################
# Logic Simulation (lsim) #
###########################
instructions = [
  'make -C  %root_dir% vcs/sim/gate/shell'
]

[vcs_logic_simulation_control]
###########################
# Lsim configurations     #
###########################

timeout = 60.0
simulation_ok_regex = 'EXIT\sSUCCESS'
test_application_time_regex = 'test application time = ([0-9]+)'
test_application_time_regex_group_no = 1

[zoix_fault_simulation]
###########################
# Fault Simulation (fsim) #
###########################
instructions = [
  'make -C %root_dir% vcs/fgen/saf',
  'make -C %root_dir% vcs/fsim/gate/shell'
]

[zoix_fault_simulation_control]
###########################
# Fsim configurations     #
###########################
timeout = 360.0
allow_regexs = ['Info: Connected to started server']

[fault_report]
###########################
# Z01X Fsim Report        #
###########################
frpt_file = '%root_dir%/run/vc-z01x/fsim_attr'
coverage_formula = 'Observational Coverage'

[preprocessing]
###########################
# Trace required          #
###########################
processor_name = 'CV32E40P'
processor_trace = '%sbst_dir%/trace.log'
elf_file = '%sbst_dir%/sbst.elf'
zoix_to_trace = { 'PC_ID' = 'PC', 'sim_time' = 'Time'}
