name: Unit Tests for asm.py

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd src/ 
        pip install -e .
        pip install toml

    - name: Codeline Test Cases
      run: |
        cd src/unit_tests
        python3 -m unittest test_asm.CodelineTest

    - name: ISA Test Cases
      run: |
        cd src/unit_tests
        python3 -m unittest test_asm.ISATest
      
    - name: AssemblyHandler Test Cases
      run: |
        cd src/unit_tests
        python3 -m unittest test_asm.AssemblyHandlerTest    

    - name: All Test Cases
      run: |
        cd src/unit_tests
        python3 -m unittest test_asm