name: Linting checks for all .py sources
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Lint asm.py 
      run: |
        cd src/testcrush
        flake8 asm.py --max-line-length 120

    - name: Lint zoix.py
      run: |
        cd src/testcrush
        flake8 asm.py --max-line-length 120
        flake8 zoix.py --max-line-length 120

    - name: Lint a0.py
      run: |
        cd src/testcrush
        flake8 a0.py --max-line-length 120

    - name: Lint utils.py
      run: |
        cd src/testcrush
        flake8 utils.py --max-line-length 120
    
    - name: Lint config.py
      run: |
        cd src/testcrush
        flake8 config.py --max-line-length 120
    
    - name: Lint transformers.py
      run: |
        cd src/testcrush/grammars
        flake8 transformers.py --max-line-length 120
