name: Python3 Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: (asm.py) Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd src/ 
        pip install -e .
        pip install toml
        pip install lark

    - name: (asm.py) Codeline Test Cases
      run: |
        cd src/unit_tests
        python3 -m unittest test_asm.CodelineTest

    - name: (asm.py) ISA Test Cases
      run: |
        cd src/unit_tests
        python3 -m unittest test_asm.ISATest
      
    - name: (asm.py) AssemblyHandler Test Cases
      run: |
        cd src/unit_tests
        python3 -m unittest test_asm.AssemblyHandlerTest    

    - name: (asm.py) All Test Cases
      run: |
        cd src/unit_tests
        python3 -m unittest test_asm

    - name: (zoix.py) Fault Test Cases
      run: |
        cd src/unit_tests
        python3 -m unittest test_zoix.FaultTest

    - name: (zoix.py) CSVFaultReport Test Cases
      run: |
        cd src/unit_tests
        python3 -m unittest test_zoix.CSVFaultReportTest

    - name: (zoix.py) ZoixInvoker Test Cases
      run: |
        cd src/unit_tests
        python3 -m unittest test_zoix.ZoixInvokerTest
      
    - name: (zoix.py) All Test Cases
      run: |
        cd src/unit_tests
        python3 -m unittest test_zoix
    
    - name: (config.py) All Test Cases
      run: |
        cd src/unit_tests
        python3 -m unittest test_config

    - name: (grammars/transformers.py) FaultListTransformer Tests Cases
      run: |
        cd src/unit_tests
        python3 -m unittest test_transformers
